### PR TITLE
Make the commit delay increment overridable

### LINKED ISSUE #179: Allow overriding CommitDelayIncrement
#### Is your feature related to a problem? Please describe.

The default [CommitDelayIncrement](https://github.com/Particular/NServiceBus.TransactionalSession/blob/main/src/NServiceBus.TransactionalSession/OpenSessionOptions.cs#L36) is set to two seconds and cannot be modified.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by danielmarbach**
Resolves:

- #179 

- [ ] Documentation update

### CODE REVIEW

**Review by andreasohlund — APPROVED** [review]

**Review by tmasternak — APPROVED** [review]

**Review by SzymonPobiega — APPROVED** [review]

**Comment by ramonsmits** [comment]
Why not merge:

- https://github.com/Particular/NServiceBus.TransactionalSession/pull/182

**Review by ramonsmits — DISMISSED** [review]
Why not do:

- https://github.com/Particular/NServiceBus.TransactionalSession/pull/182

**Comment by ramonsmits** [comment]
> Furthermore, one of the original design tradeoffs we did was also offloading the more heavy sends (actual operations) to the background while on the front-end part doing the lighter weight ones. Your spike proposes to change that,

@danielmarbach The spike does dispatching async and is not blocking the callee but yes the work is done in-process and adds only a little IO under 99% of cases.

By merging this PR we are sort of improving the situation. Especially combined with much shorter delayed retry intervals but I don't think that is the right approach. In fact, I think it is an unwise strategy as it is highly dependent on other recoverability settings. The delayed send should only exist as a fallback and not be the *primary* method to dispatch.

How about this alternative that is more aligned with your original design:

1. Send delayed outbox dispatch message
1. Commit/store database changes
1. Send same outbox dispatch message

This way the 2nd non-delayed dispatch message will give only the transport roundtrip latency as the outbox dispatch delay (that can only be mitigated using the method of #182).

Tat is by far the best trade off and IMHO much preferred over this PR to make the delay overridable **to lower dispatch latency**.

**Comment by SzymonPobiega** [comment]
@ramonsmits Laila and I are working on an enhancement release now and we would like to look at your spike PR. I hope we could merge it.

**Review by lailabougria — APPROVED** [review]
As there's no certainty we can merge the PR @ramonsmits linked, I think this can be a small step forward ensuring that there's something to address this in the short term? Approving.

**Pull request merged**
